project:
  name: niamoto-og
  version: 1.0.0
  created_at: '2025-09-30T09:00:00.000000'
  niamoto_version: 0.7.0
database:
  path: db/niamoto.db
logs:
  path: logs
exports:
  web: exports/web # web root directory
  api: exports/api # api root directory
plugins:
  path: plugins # Path to the project plugins directory
templates:
  path: templates # Path to the project templates directory
