taxonomy:
  path: imports/occurrences.csv
  hierarchy:
    levels:
    - name: family
      column: family
    - name: genus
      column: genus
    - name: species
      column: species
    - name: infra
      column: infra
    taxon_id_column: id_taxonref
  api_enrichment:
    enabled: false
    plugin: api_taxonomy_enricher
    api_url: https://api.endemia.nc/v1/taxons
    auth_method: api_key
    auth_params:
      key: 1e106508-9a86-4242-9012-d6cafdea3374
      location: header
      name: apiKey
    query_params:
      section: flore
      maxitem: '1'
      excludes: meta,links
      includes: images
    query_field: full_name
    rate_limit: 2
    cache_results: true
    response_mapping:
      id_endemia: id
      id_florical: id_florical
      endemia_url: endemia_url
      endemic: endemique
      protected: protected
      protected_provnord: protected_provnord
      protected_provsud: protected_provsud
      redlist: redlist
      redlist_cat: categorie_uicn
      image_small_thumb: image.small_thumb
      image_big_thumb: image.big_thumb
      image_auteur: image.auteur
      images: images
plots:
  type: csv
  path: imports/plots.csv
  identifier: id_plot
  locality_field: plot
  location_field: geo_pt
  link_field: locality
  occurrence_link_field: plot_name
occurrences:
  type: csv
  path: imports/occurrences.csv
  identifier: id_taxonref
  location_field: geo_pt
shapes: null
layers:
- name: forest_cover
  type: vector
  format: shapefile
  path: imports/layers/amap_carto_3k_20240715.gpkg
  description: Forest cover layer
- name: elevation
  type: raster
  path: imports/layers/mnt100_epsg3163.tif
  description: Digital elevation model
- name: rainfall
  type: raster
  path: imports/layers/rainfall_epsg3163.tif
  description: Annual rainfall distribution
- name: holdridge
  type: raster
  path: imports/layers/amap_raster_holdridge_nc.tif
  description: Holdridge
